{
  "formatVersion": "1.1",
  "component": {
    "group": "org.usfirst.frc.team4999",
    "module": "neopixel-leds",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "neopixel-leds-2.0.jar",
          "url": "neopixel-leds-2.0.jar",
          "size": 51202,
          "sha512": "ff8bd3f4392c923eaac1ac77b76113c4f67deec34bf2fb166513d02da43b38b83e559f493492c6d0f7c0a603498b228d50a2ae0a695bc97480edd2dd1b59b93f",
          "sha256": "97a4f6cbe3176240eab7654244fc1bf2cfb840c05394394183515cafabc90ed8",
          "sha1": "9b3e7c4b63c92a1b3394d58ca6925cdacfa5b0c3",
          "md5": "1b36d30da7cce618a5094c286b81580e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-2.0.jar",
          "url": "neopixel-leds-2.0.jar",
          "size": 51202,
          "sha512": "ff8bd3f4392c923eaac1ac77b76113c4f67deec34bf2fb166513d02da43b38b83e559f493492c6d0f7c0a603498b228d50a2ae0a695bc97480edd2dd1b59b93f",
          "sha256": "97a4f6cbe3176240eab7654244fc1bf2cfb840c05394394183515cafabc90ed8",
          "sha1": "9b3e7c4b63c92a1b3394d58ca6925cdacfa5b0c3",
          "md5": "1b36d30da7cce618a5094c286b81580e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-2.0-javadoc.jar",
          "url": "neopixel-leds-2.0-javadoc.jar",
          "size": 208184,
          "sha512": "5b0a549dadeea52a510e0941fea8f8c083c27fd5af53ae7ba6078ee106abf749bafb0ab14fca847af10d235f5f422f59156719131cc58ef93d10d5ce1293c7bb",
          "sha256": "845cceefea80685d74f083605eb865e06ef8b489f41c12183219fc9a58b8649a",
          "sha1": "0f517725417aad5d8c0b0cb9b9d8c9908f3f9b39",
          "md5": "a692de0e6d720cb6e7bd3b50084428dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-2.0-sources.jar",
          "url": "neopixel-leds-2.0-sources.jar",
          "size": 31905,
          "sha512": "f778d7800e4b4c58afd63a5723be63f1ce8b23e6a9492ca37acab6c23559030c6f3e7642ad65251d9b4f4a353f4d85afd9c62e18ba67bc13ac3d03460c21eac4",
          "sha256": "bb1e20b936d72ddebd9cc5a4be7a9d6b15355277b9321465aaa47bb62299a962",
          "sha1": "89b4ed95c8f24ce2eaff3a78a723daede643dc67",
          "md5": "46fef59786a01290c6448f4f2e698435"
        }
      ]
    }
  ]
}
