{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momentum4999.motune",
    "module": "motune-core",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "motune-core-0.2.1.jar",
          "url": "motune-core-0.2.1.jar",
          "size": 19064,
          "sha512": "07c667da45e6c407db69bc1ab7ad4fadc5d878ac88ceeb6baec91638d0bbc4b3de0bd938ab12f3f8ef34f5a799f76c5dbe2ba8f0bc48592a192e7a0f1a894c79",
          "sha256": "451bf617bd70c13b8ece0ca4d46f5530d7872eb855b12682a787ead7e95e39ff",
          "sha1": "23fd451bc47ed35d292a41194ffb5cff272454d2",
          "md5": "a78c27c03af376c79f8c35ab7f8d5665"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ini4j",
          "module": "ini4j",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "motune-core-0.2.1.jar",
          "url": "motune-core-0.2.1.jar",
          "size": 19064,
          "sha512": "07c667da45e6c407db69bc1ab7ad4fadc5d878ac88ceeb6baec91638d0bbc4b3de0bd938ab12f3f8ef34f5a799f76c5dbe2ba8f0bc48592a192e7a0f1a894c79",
          "sha256": "451bf617bd70c13b8ece0ca4d46f5530d7872eb855b12682a787ead7e95e39ff",
          "sha1": "23fd451bc47ed35d292a41194ffb5cff272454d2",
          "md5": "a78c27c03af376c79f8c35ab7f8d5665"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "motune-core-0.2.1-javadoc.jar",
          "url": "motune-core-0.2.1-javadoc.jar",
          "size": 261,
          "sha512": "b7c5e74a639310e28ea4aaefaaa316dd5b945adc264de0d60e3b30739d4dd9a5da75c11708033e78734081b6869aa8b3917c81a096e6ca8ecd2fa08784b5faaf",
          "sha256": "86241115f8cfc7cd98782dd2bd2eb77ab158d907f051ee7050248f463d22e4b0",
          "sha1": "81a46d298bd1787e9824b3299303c4fe49158855",
          "md5": "5f357f131b99b445b095c042633d594c"
        }
      ]
    }
  ]
}
