{
  "formatVersion": "1.1",
  "component": {
    "group": "org.usfirst.frc.team4999",
    "module": "neopixel-leds-wpilibj",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "neopixel-leds-wpilibj-3.0.jar",
          "url": "neopixel-leds-wpilibj-3.0.jar",
          "size": 6243,
          "sha512": "f93e012522bbf910be8fc72fe48e23a5277bc69282f52f5169a4c9702d94491994bc8d91565be87f3b342aff672c1606fae7791b6f23f97d5100e5791fce0f35",
          "sha256": "5988c7c1986a54dbfb25a299ed66eac6ba9fa73bd8d0562a2788a255e2f15ff6",
          "sha1": "bbe1e239074548bb96e9552ab6e0f7859d077203",
          "md5": "73c4a91aa7ebbbe631fb6175174e8004"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.usfirst.frc.team4999",
          "module": "neopixel-leds",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2023.4.2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2023.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "neopixel-leds-wpilibj-3.0.jar",
          "url": "neopixel-leds-wpilibj-3.0.jar",
          "size": 6243,
          "sha512": "f93e012522bbf910be8fc72fe48e23a5277bc69282f52f5169a4c9702d94491994bc8d91565be87f3b342aff672c1606fae7791b6f23f97d5100e5791fce0f35",
          "sha256": "5988c7c1986a54dbfb25a299ed66eac6ba9fa73bd8d0562a2788a255e2f15ff6",
          "sha1": "bbe1e239074548bb96e9552ab6e0f7859d077203",
          "md5": "73c4a91aa7ebbbe631fb6175174e8004"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-wpilibj-3.0-javadoc.jar",
          "url": "neopixel-leds-wpilibj-3.0-javadoc.jar",
          "size": 78445,
          "sha512": "dca06bd83cd5430d963bf28e59b563f09c694fbb5150879a4e5c4f7bd65c5fbbbf6e179f3bbeabec37abeeb7713dbcc3378a22a2d94696c13c172bfdb7d021ab",
          "sha256": "50404a52c6fd7d5471740de717ccfba2b15ec03f59f3589da599e74009bbd0ff",
          "sha1": "5e73d8c04e032f856e3c4d176df541b914c2fce4",
          "md5": "6f30b3f15318fc981da1c4e6def13030"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-wpilibj-3.0-sources.jar",
          "url": "neopixel-leds-wpilibj-3.0-sources.jar",
          "size": 3056,
          "sha512": "91182e43451017529399b9cdd83c19c732994ea9bad6b02a745cb89cedb795321c00777c26673e2070e8fe254ce08ef7cddff934595477cc8dcff2e445bfafc7",
          "sha256": "00d9033f2f94839d8e7e5d776a99e07d00a73b852204de75a8577c65b2d7bba3",
          "sha1": "41b6e876f167beb187afa421a684280474d88047",
          "md5": "41080cc89cfc98ecc439459fb9e9d910"
        }
      ]
    }
  ]
}
