{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momentum4999.motune",
    "module": "motune-phoenix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-phoenix-0.0.1.jar",
          "url": "motune-phoenix-0.0.1.jar",
          "size": 10471,
          "sha512": "45000d3695704ab169d78bdcc093362ada4810fbfa38f891bee50c1cfb497a5f2f7b1174bc4a8b4ca10dd8ba7bf06c112e75e8f7c31236e2fa157cd7c10a96ae",
          "sha256": "508f727f59e38ebe56e3ef5597d8266691c9b1f80e02a5eb9c4e7b9391674cca",
          "sha1": "a9a4ddbf53d2d6d699239036eb82c9882a2ae975",
          "md5": "0405d3b5c6d21431a73402527ddb6040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-phoenix-0.0.1.jar",
          "url": "motune-phoenix-0.0.1.jar",
          "size": 10471,
          "sha512": "45000d3695704ab169d78bdcc093362ada4810fbfa38f891bee50c1cfb497a5f2f7b1174bc4a8b4ca10dd8ba7bf06c112e75e8f7c31236e2fa157cd7c10a96ae",
          "sha256": "508f727f59e38ebe56e3ef5597d8266691c9b1f80e02a5eb9c4e7b9391674cca",
          "sha1": "a9a4ddbf53d2d6d699239036eb82c9882a2ae975",
          "md5": "0405d3b5c6d21431a73402527ddb6040"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "motune-phoenix-0.0.1-javadoc.jar",
          "url": "motune-phoenix-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "98da8366028473fea646e46b2e68843c85ba60ed64cbd38f6b8fc5dbb4ba8874ef6112e5df3dc7cfea2718926cd80a8048863d61a3e927ceae4503b0ea2cf47a",
          "sha256": "10531ef9f09d74808e60d32aca43e277caf9fdb67eee56a0db87adeddc79d7f6",
          "sha1": "0717ae8da2ccfbba0fbe928e8f6ecf5c2dbc3ceb",
          "md5": "c868af0c3d4962b373984e8de05ebb90"
        }
      ]
    }
  ]
}
