{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momentum4999.motune",
    "module": "motune-phoenix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-phoenix-0.0.1.jar",
          "url": "motune-phoenix-0.0.1.jar",
          "size": 10471,
          "sha512": "999fe911ed071b86a2ffdeaef932cb66f6715032f6f53254a6d9230bb1a7052597746f93f8951d1809620203f88bc176be7041c62f1b645c36265bf738c6235c",
          "sha256": "74de43ec3ee0e771bf2c0168186fa768cfeddd52f94f49497f7e5d4d07e9460c",
          "sha1": "c23fcf9019eea5a617b0d40236ac36e24ed33c3f",
          "md5": "8068acf8de16c3088a3a1d4bf0aa4186"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.30.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-phoenix-0.0.1.jar",
          "url": "motune-phoenix-0.0.1.jar",
          "size": 10471,
          "sha512": "999fe911ed071b86a2ffdeaef932cb66f6715032f6f53254a6d9230bb1a7052597746f93f8951d1809620203f88bc176be7041c62f1b645c36265bf738c6235c",
          "sha256": "74de43ec3ee0e771bf2c0168186fa768cfeddd52f94f49497f7e5d4d07e9460c",
          "sha1": "c23fcf9019eea5a617b0d40236ac36e24ed33c3f",
          "md5": "8068acf8de16c3088a3a1d4bf0aa4186"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "motune-phoenix-0.0.1-javadoc.jar",
          "url": "motune-phoenix-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "4589c65bc18146c55a8248642ae7c3c829f7a2b30239382e7c274d580198497e3d417905bbc563cc42fa512e010819860cf912bb5b790580dffb02d4611c7952",
          "sha256": "018f4241120a2d90852fe74cd879b60126e8dcd57c328dd398977ced62a2b2ce",
          "sha1": "633f72be45b23aa5bcf3d34e0db71140f100685a",
          "md5": "dd36ae20ca2f518f9a2703561d4b6425"
        }
      ]
    }
  ]
}
