{
  "formatVersion": "1.1",
  "component": {
    "group": "org.usfirst.frc.team4999",
    "module": "neopixel-leds",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "neopixel-leds-3.0.jar",
          "url": "neopixel-leds-3.0.jar",
          "size": 51912,
          "sha512": "8ef0249b9fc264ae17526f7f383ec5e32b42edbb610aefce816c7955867ffef4c690314c8232575b6b9406c8202364263b020af99e2dfe6d0e5acc9945db6ab7",
          "sha256": "003c3d486fae4a90d18fc28e504c80459926daded40cbe0b184706852d84108e",
          "sha1": "876fa16697e8ad3ff323e5109747a15de53e949d",
          "md5": "20db9045d08c6c1b45b436af651b04b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-3.0.jar",
          "url": "neopixel-leds-3.0.jar",
          "size": 51912,
          "sha512": "8ef0249b9fc264ae17526f7f383ec5e32b42edbb610aefce816c7955867ffef4c690314c8232575b6b9406c8202364263b020af99e2dfe6d0e5acc9945db6ab7",
          "sha256": "003c3d486fae4a90d18fc28e504c80459926daded40cbe0b184706852d84108e",
          "sha1": "876fa16697e8ad3ff323e5109747a15de53e949d",
          "md5": "20db9045d08c6c1b45b436af651b04b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-3.0-javadoc.jar",
          "url": "neopixel-leds-3.0-javadoc.jar",
          "size": 203468,
          "sha512": "c470b5f6c18f045c6c9c8c090735c47643430fcdaa01c0a805a223ff6378c23a4778d78c893e4604df3dc382fac22b6661e048f05f586833ff614dea282866b1",
          "sha256": "352e757b19a83f3bad6561fc2a5a2a302a9f474c230266c94ffd6501a65bd3d0",
          "sha1": "b36ac44020db0f8801fefe8e29b2a19e1fe97bad",
          "md5": "ec230a482fe79a59cb668af18c4515a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neopixel-leds-3.0-sources.jar",
          "url": "neopixel-leds-3.0-sources.jar",
          "size": 31445,
          "sha512": "dd008cfa56c649ec06e2478d31574f5e3369fc93363f43758b05775c432a16bb891e8cb6bc29472b4d55eb6604b7f570034a472f5d655b9ca76b63b9fbc72e3c",
          "sha256": "626666dd7743f2bb50d75b07e323f989cc5be86681df990bc84d15b26b720cf1",
          "sha1": "aa5697d0f652b302773de2c27447fd79e19840e4",
          "md5": "ef6b50b39d46eb36a7fee06e15da410f"
        }
      ]
    }
  ]
}
