{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momentum4999.motune",
    "module": "motune-revlib",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2023.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-revlib-0.0.1.jar",
          "url": "motune-revlib-0.0.1.jar",
          "size": 16285,
          "sha512": "6b0c7be6694c98078813bb60bf75d6366b32c16f99638eb39bb928fdcc1490e61329ab55d1538b784c1117cdac08b48b669bf898fa401a9819351f4cc863d763",
          "sha256": "be1276195c457a9d16c91a76e532b7510372031f60913771f474ec215fd88b4f",
          "sha1": "31ce5765180681616ad10a00427d9b9b9e26b795",
          "md5": "143d1b4382fab6d2b36e585d954df793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2023.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-revlib-0.0.1.jar",
          "url": "motune-revlib-0.0.1.jar",
          "size": 16285,
          "sha512": "6b0c7be6694c98078813bb60bf75d6366b32c16f99638eb39bb928fdcc1490e61329ab55d1538b784c1117cdac08b48b669bf898fa401a9819351f4cc863d763",
          "sha256": "be1276195c457a9d16c91a76e532b7510372031f60913771f474ec215fd88b4f",
          "sha1": "31ce5765180681616ad10a00427d9b9b9e26b795",
          "md5": "143d1b4382fab6d2b36e585d954df793"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "motune-revlib-0.0.1-javadoc.jar",
          "url": "motune-revlib-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "88f65917098db0d17b585616fd2970b9ce9d7495e5d37b0ced1b20e343455d75c86ee78bad638fba6d048c2f003ad04f9e13222c1a1cdf154d0303db93c2bff4",
          "sha256": "d299a3b6a4a2b0a0bffd265dc107e79764f0e82c6d3609a4801e85e81f273dc5",
          "sha1": "e3e2114ea8e5045bf61a315a4150e4697724bce4",
          "md5": "1721f105a9f9adc7e3acbe3020c1487e"
        }
      ]
    }
  ]
}
