{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momentum4999.motune",
    "module": "motune-revlib",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2023.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-revlib-0.0.1.jar",
          "url": "motune-revlib-0.0.1.jar",
          "size": 16285,
          "sha512": "ea7d66fa0ac28b9c202775b62914ad6c23a0e73091983f998aa326f392699a42165dd2221b2b00c692aece11680399c5b7c05e7e7002cc32a1e23edfbf62275b",
          "sha256": "acddc5e6a312cfdffcd7a9bf968b79cd8db478bf7cab297d5462131048193925",
          "sha1": "bca94a5cc01388c0a6da7bd902963b9c2903e000",
          "md5": "89fcbf56cade8447a85378237e7768dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2023.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "motune-revlib-0.0.1.jar",
          "url": "motune-revlib-0.0.1.jar",
          "size": 16285,
          "sha512": "ea7d66fa0ac28b9c202775b62914ad6c23a0e73091983f998aa326f392699a42165dd2221b2b00c692aece11680399c5b7c05e7e7002cc32a1e23edfbf62275b",
          "sha256": "acddc5e6a312cfdffcd7a9bf968b79cd8db478bf7cab297d5462131048193925",
          "sha1": "bca94a5cc01388c0a6da7bd902963b9c2903e000",
          "md5": "89fcbf56cade8447a85378237e7768dc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "motune-revlib-0.0.1-javadoc.jar",
          "url": "motune-revlib-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "4589c65bc18146c55a8248642ae7c3c829f7a2b30239382e7c274d580198497e3d417905bbc563cc42fa512e010819860cf912bb5b790580dffb02d4611c7952",
          "sha256": "018f4241120a2d90852fe74cd879b60126e8dcd57c328dd398977ced62a2b2ce",
          "sha1": "633f72be45b23aa5bcf3d34e0db71140f100685a",
          "md5": "dd36ae20ca2f518f9a2703561d4b6425"
        }
      ]
    }
  ]
}
