{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momentum4999.motune",
    "module": "motune-revlib",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2023.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2023.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "motune-revlib-0.0.1.jar",
          "url": "motune-revlib-0.0.1.jar",
          "size": 15978,
          "sha512": "d4a1534eb2ba90fe2239fb5242fc8bdfd9c2a751c8f2df54011acc2783fb3f784cf7c30f87dc395524185b1f11e529cd0367a3d812c741414395efbba26a9b8e",
          "sha256": "6b548ee1ceaffb5dc306b36d6968d373aa8c1b47780526b1da6616fa1e277c3a",
          "sha1": "06cd538a573f748c5d42865d86001e87945ba2c6",
          "md5": "50ac5805f02609b44a4d0f0d6dfc634a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.momentum4999.motune",
          "module": "motune-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2023.1.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2023.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "motune-revlib-0.0.1.jar",
          "url": "motune-revlib-0.0.1.jar",
          "size": 15978,
          "sha512": "d4a1534eb2ba90fe2239fb5242fc8bdfd9c2a751c8f2df54011acc2783fb3f784cf7c30f87dc395524185b1f11e529cd0367a3d812c741414395efbba26a9b8e",
          "sha256": "6b548ee1ceaffb5dc306b36d6968d373aa8c1b47780526b1da6616fa1e277c3a",
          "sha1": "06cd538a573f748c5d42865d86001e87945ba2c6",
          "md5": "50ac5805f02609b44a4d0f0d6dfc634a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "motune-revlib-0.0.1-javadoc.jar",
          "url": "motune-revlib-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "88f65917098db0d17b585616fd2970b9ce9d7495e5d37b0ced1b20e343455d75c86ee78bad638fba6d048c2f003ad04f9e13222c1a1cdf154d0303db93c2bff4",
          "sha256": "d299a3b6a4a2b0a0bffd265dc107e79764f0e82c6d3609a4801e85e81f273dc5",
          "sha1": "e3e2114ea8e5045bf61a315a4150e4697724bce4",
          "md5": "1721f105a9f9adc7e3acbe3020c1487e"
        }
      ]
    }
  ]
}
